# Generated by Django 3.2.6 on 2021-08-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='has_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
