# Generated by Django 3.2.6 on 2021-08-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_dbs',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_sites',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_storage',
            field=models.FloatField(default=1024),
        ),
    ]
