# Generated by Django 3.2.6 on 2021-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='storage_used',
            field=models.FloatField(default=1024),
        ),
    ]
