# Generated by Django 3.2.6 on 2021-08-11 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_website_has_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
