# Generated by Django 3.2.6 on 2021-08-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_database_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='username',
            field=models.SlugField(unique=True),
        ),
    ]
