# Generated by Django 3.2.6 on 2021-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_storage_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storage_used',
            field=models.FloatField(default=0),
        ),
    ]
