# Generated by Django 3.2.6 on 2021-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_storage_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_sites',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
