# Generated by Django 3.2.6 on 2021-08-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_max_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_sites',
            field=models.IntegerField(default=10),
        ),
    ]
