# Generated by Django 3.2.6 on 2021-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_max_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_wp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='website',
            name='php',
            field=models.CharField(choices=[('7.1', 'PHP 7.1')], max_length=20),
        ),
    ]
