# Generated by Django 3.2.6 on 2021-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_file_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='dir_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('file', 'File'), ('directory', 'Directory')], max_length=10),
        ),
    ]
