# Generated by Django 3.2.6 on 2021-08-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210812_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='dir_level',
            new_name='level',
        ),
    ]
