# Generated by Django 3.2.6 on 2021-08-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_dir_level_file_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='chmod',
            new_name='permissions',
        ),
    ]
