# Generated by Django 3.2.6 on 2021-08-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210813_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='level',
        ),
    ]
