# Generated by Django 3.2.6 on 2021-08-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_file_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
