package templates

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"text/template"
)

// WordPressConfig holds WordPress configuration
type WordPressConfig struct {
	DBName     string
	DBUser     string
	DBPassword string
	DBHost     string
	TablePrefix string
	Debug      bool
	
	// Generated keys
	AuthKey        string
	SecureAuthKey  string
	LoggedInKey    string
	NonceKey       string
	AuthSalt       string
	SecureAuthSalt string
	LoggedInSalt   string
	NonceSalt      string
}

const wpConfigTemplate = `<?php
/**
 * WordPress Configuration - Generated by FastCP
 */

// Database settings
define('DB_NAME', '{{.DBName}}');
define('DB_USER', '{{.DBUser}}');
define('DB_PASSWORD', '{{.DBPassword}}');
define('DB_HOST', '{{.DBHost}}');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

// Authentication Keys and Salts
define('AUTH_KEY',         '{{.AuthKey}}');
define('SECURE_AUTH_KEY',  '{{.SecureAuthKey}}');
define('LOGGED_IN_KEY',    '{{.LoggedInKey}}');
define('NONCE_KEY',        '{{.NonceKey}}');
define('AUTH_SALT',        '{{.AuthSalt}}');
define('SECURE_AUTH_SALT', '{{.SecureAuthSalt}}');
define('LOGGED_IN_SALT',   '{{.LoggedInSalt}}');
define('NONCE_SALT',       '{{.NonceSalt}}');

// Table prefix
$table_prefix = '{{.TablePrefix}}';

// Debug mode
define('WP_DEBUG', {{if .Debug}}true{{else}}false{{end}});
{{if .Debug}}
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
{{end}}

// Security
define('DISALLOW_FILE_EDIT', true);
define('FORCE_SSL_ADMIN', true);

// Performance
define('WP_MEMORY_LIMIT', '256M');
define('WP_MAX_MEMORY_LIMIT', '512M');

// Absolute path to the WordPress directory
if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

// Sets up WordPress vars and included files
require_once ABSPATH . 'wp-settings.php';
`

// GenerateWPConfig generates a wp-config.php file
func GenerateWPConfig(config *WordPressConfig) (string, error) {
	// Generate keys if not provided
	if config.AuthKey == "" {
		config.AuthKey = generateWPKey()
		config.SecureAuthKey = generateWPKey()
		config.LoggedInKey = generateWPKey()
		config.NonceKey = generateWPKey()
		config.AuthSalt = generateWPKey()
		config.SecureAuthSalt = generateWPKey()
		config.LoggedInSalt = generateWPKey()
		config.NonceSalt = generateWPKey()
	}

	if config.DBHost == "" {
		config.DBHost = "localhost"
	}

	if config.TablePrefix == "" {
		config.TablePrefix = "wp_"
	}

	tmpl, err := template.New("wp-config").Parse(wpConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, config); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

func generateWPKey() string {
	bytes := make([]byte, 32)
	rand.Read(bytes)
	return hex.EncodeToString(bytes)
}
